POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "userName": "ssdssdtest",
    "password": "1231bnbn23",
    "name": "son"
}

###
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "userName": "ssdssdtest",
    "password": "1231bnbn23"
}